version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11.5
  pre_build:
    commands:
      - echo "Installing Docker..."
      - apt update -y
      - apt install -y docker.io
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t todoapp:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to S3...
      - aws s3 cp imagedefinitions.json s3://todoapp-prod/imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json