version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11.5
  pre_build:
    commands:
      - apt-get update -y
      - apt-get install -y pip
  build:
    commands:
      - pip install -r requirements.txt
      - uvicorn main:app --port 10000 --reload
  
artifacts: 
  files:
    - "**/*"