version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11.5
  pre_build:
    commands:
      - echo "Installing Docker..."
      - apt-get update -y
      - apt-get install -y docker.io
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t todoapp:latest .
  
artifacts: 
  files:
    - "**/*"